### PR TITLE
Optimized checkstyle check workflow. Check/test time reduced.

### LINKED ISSUE #1064: Bug: Checkstyle workflow does not scale with full sequential coordinate sweep
### Describe the bug

The current checkstyle workflow scales poorly because it runs the full checkstyle sweep sequentially across the entire coordinate set. At the current repository size, this is too expensive for a single GitHub Actions job and causes timeout-driven failures even when individual coordinate checks are healthy.

### Steps to reproduce

```markdown
1. Run the current full checkstyle path locally:

./gradlew spotlessCheck checkstyle --console=plain

2. Observe that `checkstyle` executes nested per-coordinate Gradle builds sequentially.
3. Compare with sharded execution:

./gradlew checkstyle -Pcoordinates=1/8 --console=plain
...
./gradlew checkstyle -Pcoordinates=8/8 --console=plain
```

### Expected behavior

The repository should have a long-term checkstyle strategy that scales with the number of supported coordinates and does not require a full sequential sweep in one CI job.

### Logs and error messages (#1062 )

```text
Observed during investigation for PR #1062 :

- The repository currently exposes about 1332 coordinates.
- A local full run projected to well over 20 minutes and likely around an hour or more for a full sequential sweep.
- An 8-shard GitHub diagnostic passed, with each shard taking about 12m 43s.
- That implies the old single-job approach is too large for one runner and would take roughly 1h 40m if executed sequentially.

This indicates the issue is workload size, not a single failing coordinate.
```

### Reproducer (optional)

_No response_

### Additional context

Short-term mitigation:
- shard the existing full checkstyle workload

Long-term fix:
- stop using a broad full sequential checkstyle sweep for every relevant PR
- run checkstyle only for changed coordinates
- use a smaller representative set for infrastructure/workflow changes
- reduce CI cost rather than scaling by adding more shards indefinitely

### GraalVM version

Oracle GraalVM 21.0.10

### Operating system

MAC

### CPU architecture

AMD64 (x86-64)

### PR DESCRIPTION
**Pull request by oleksii-tumanov**
## What does this PR do?

Fixes #1064 by changing the Checkstyle workflow

This PR now:
- runs Checkstyle only for changed coordinates
- runs a subset only when build logic or the checkstyle workflow changes
- use a single 'checkstyle' status 
- adds tests for the selection logic

## Checklist before merging
- [x] I have considered including reachability metadata directly in the library or the framework (see [our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md))
- [x] I am the original author of all content provided in the pull request, and I did not copy the content from any other source (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#tests))
- [x] For all tests where I am not the sole author, I have added a comment that proves I may publish them under the specified license (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#tests))
- [x] I have properly formatted metadata files (see [our formatting guide](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#format-metadata-files))
- [x] I have added thorough tests (see [the tests section from our contributing document](https://github.com/oracle/graalvm-reachability-metadata/blob/master/CONTRIBUTING.md#Tests))
- [x] I have filled all places where my pull request accesses files, network, docker, or any other external service (see the section above)

### CODE REVIEW

File: tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/harness/TckExtensionTests.java [hunk 1]
```diff
@@ -89,9 +157,84 @@ private TckExtension createExtension(String metadataIndexJson) throws IOExceptio
...
                 .build();
         return project.getExtensions().create("tck", TckExtension.class, project);
     }
+
+    private void createLibrary(String group, String artifact, String version) throws IOException {
+        String metadataIndex = """
+                [
+                  {
+                    "latest": true,
+                    "module": "%s:%s",
```
Comment (jvukicev) [inline tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/harness/TckExtensionTests.java]: With the 1.0-M1 release of the reachability metadata repository, module is no longer a field in the index.json. You can generally refer to metadata/schemas/metadata-library-index-schema-v2.0.0.json for the new format of the index file, but I believe that removing the module field should be enough here.

File: tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/harness/TckExtensionTests.java [hunk 2]
```diff
@@ -89,9 +157,84 @@ private TckExtension createExtension(String metadataIndexJson) throws IOExceptio
...
+        Files.writeString(
+                testsRoot.resolve(capitalize(artifact) + "Test.java"),
+                "package %s;\nclass %sTest {}\n".formatted(javaPackage, capitalize(artifact))
+        );
+
+        Files.createDirectories(tempDir.resolve("tests/tck-build-logic"));
+        Files.writeString(tempDir.resolve("LICENSE"), "test");
+    }
+
+    private void writeRootMetadataIndex(String rootMetadataIndex) throws IOException {
```
Comment (jvukicev) [inline tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/harness/TckExtensionTests.java]: Also with the 1.0-M1 release, this "global" metadata/index.json is no longer a file we support. All metadata resolution is now done through path resolution with given artifact coordinates.

File: tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/MetadataFilesCheckerTaskTests.java
Comment (jvukicev) [inline tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/MetadataFilesCheckerTaskTests.java:22]: Same as the comments in `TckExtensionTests.java`.

File: tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle [hunk 3]
```diff
@@ -205,6 +205,43 @@ Map<String, List<String>> matrixDefaultsFor(String section) {
     ]
 }
 
+Map<String, List<String>> coordinatesOnlyMatrix(List<String> coordinates) {
+    [
+            "coordinates": coordinates
+    ]
+}
+
+Closure<List<String>> representativeInfrastructureCoordinates = {
```
Comment (jvukicev) [inline tests/tck-build-logic/src/main/groovy/org.graalvm.internal.tck-harness.gradle]: I don't feel that we need to extract this part out of `generateInfrastructureChangedCoordinatesMatrix` (if we don't test `checkstyle` on infra changes).

File: .github/workflows/checkstyle.yml [hunk 4]
```diff
@@ -8,31 +8,57 @@ concurrency:
...
+      infra-matrix: ${{ steps.infra-matrix.outputs.matrix }}
     steps:
       - name: "☁️ Checkout repository"
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-      - name: "🔎 Detect relevant file changes"
-        id: filter
+      - name: "Detect infra changes"
```
Comment (jvukicev) [inline .github/workflows/checkstyle.yml]: I don't see the need for "infra changes" checkstyle? The infra changes matrix generation exists so we know we didn't break our TCK with our infra changes. But checking style on for random libraries metadata on every infra change seems unnecessary to me.

Thoughts @vjovanov ?

File: tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/TckExtension.java [hunk 5]
```diff
@@ -204,26 +180,67 @@ List<String> diffCoordinates(String baseCommit, String newCommit) {
         return changedCoordinates;
     }
 
+    /**
+     * Returns a list of coordinates whose test sources changed between baseCommit and newCommit.
+     *
+     * @return List of coordinates
+     */
+    @SuppressWarnings("unused")
+    public List<String> diffTestCoordinates(String baseCommit, String newCommit) {
```
Comment (jvukicev) [inline tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/TckExtension.java]: Why do we need this? I feel like checkstyle should run on all coordinates gathered by `diffCoordinates`, as we also want to checkstyle a library whose metadata changed, so we know that the metadata is formatted properly.

File: tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/harness/TckExtensionTests.java (hunk 1 above)
Comment (oleksii-tumanov) [reply tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/harness/TckExtensionTests.java]: let me review M1 release and changes in the format

File: tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/harness/TckExtensionTests.java (hunk 2 above)
Comment (oleksii-tumanov) [reply tests/tck-build-logic/src/test/java/org/graalvm/internal/tck/harness/TckExtensionTests.java]: I'll update it. Thank you!

File: tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/TckExtension.java (hunk 5 above)
Comment (oleksii-tumanov) [reply tests/tck-build-logic/src/main/groovy/org/graalvm/internal/tck/harness/TckExtension.java]: Originally, idea was build/time reduction. I thought that diffTestCoordinates covers changed test sources and spotlessCheck covers formatting for metadata changes (JSON). 
 
 I think you a right. That split adds more complexity then value for the project. Let me revert it back to diffCoordinates.

File: .github/workflows/checkstyle.yml (hunk 4 above)
Comment (oleksii-tumanov) [reply .github/workflows/checkstyle.yml]: My initial thought was to test full flow on infra changes, just to make sure the integration still works correctly end to end.

But I agree checkstyle is not the right place here. We already have the dedicated infra test workflow. I'll remove the infra-specific checkstyle part.

**Comment by vjovanov** [comment]
Can we test this PR by changing two coordinates: one with good style and one with broken style?

We can remove that commit after we see it works.

**Comment by oleksii-tumanov** [comment]
> Can we test this PR by changing two coordinates: one with good style and one with broken style?
> 
> We can remove that commit after we see it works.


Yes, it make sense.
Added few comments. 1 short (valid) and 1 long (invalid).

Screenshot 2026-03-19 at 02 34 56
